spring:
  application:
    name: ecommerceManager
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://52.90.249.215:8080/realms/TMSBackend
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://152.90.249.215:5432/ecommerceDB
    username: dom
    password: dom

  jpa:
    properties:  
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        ddl-auto: update 

  h2:
    console:
      enabled: true

jwt:
  auth:
    converter:
      resource-id: TMSBackendClient
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8090'
  servlet:
    context-path: /api
